### ISSUE TITLE
Support dictionary arguments

### ISSUE THREAD

**Issue by amittendulkar** [chonla/robotframework-stringformat#1]
Please add another `**kwargs` argument to the keyword that can be passed on to str.format() as `pattern.format(*args, **kwargs)`

This will allow passing dictionary with key-value pairs to be replaced. E.g.
```
&{url data}=    Create Dictionary    hostname=myhost    domain=foo.com    port=8080
${url}=    Format String    http://{hostname}.{domain}:{port}    &{url data}
```

**Comment by chonla** [comment]
@amittendulkar Thank you for your feedback.

Done in 54cce955f26fca553d86123db9acd9a58c3ddc87 and published to pypi.
You can upgrade with `pip install -U robotframework-stringformat`.

**Comment by amittendulkar** [comment]
Thanks.
